backend:
  name: git-gateway
  branch: main  # or 'master', depending on your repo

media_folder: "/assets/"   # files go here
public_folder: "/assets/"

publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'markdown'
    format: 'frontmatter'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover Image', name: 'image', widget: 'image', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Categories', name: 'categories', widget: 'string', required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: true, default: 'rishabh' }
      - { label: 'Share', name: 'share', widget: 'boolean', default: true, required: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'drafts'
    label: 'Drafts'
    folder: '_drafts/'
    create: true
    slug: '{{slug}}'
    extension: 'markdown'
    format: 'frontmatter'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
